/**
* DO NOT EDIT THIS FILE.
* @preserve
**/
(function () {
  if (typeof window.styleguide === 'undefined') window.styleguide = {};
  if (typeof window.styleguide.components === 'undefined') window.styleguide.components = {};
  window.styleguide.components = {
    atoms: {},
    molecules: {},
    organisms: {}
  }
})();
