name: Drupal-KIT
recipe: drupal10
exlodes:
  - drush
  - node_modules
  - themesrc/node_modules
  - docroot/core
  - docroot/vendor
  - docroot/modules/contrib
config:
  php: '8.1'
  webroot: docroot
  composer_version: 2
services:
  appserver:
    xdebug: true
    build:
      - composer install
  database:
    creds:
      user: user
      password: user
      database: www
  node:
    type: node
    build:
      - npm install
      - npm install -G gulp
      - cd /app/source && npm install
      - cd /app/source && npm run gulp
tooling:
  node:
    service: node
  npm:
    service: node
    dir: /app/source
  gulp:
    service: node
    dir: /app/source
  run_init:
    cmd:
      - appserver: composer install
      - node: npm install
      - node: npm install -G gulp
      - node: cd /app/source && npm install
      - node: cd /app/source && npm run gulp
