#!/usr/bin/env bash

#: exec_target = cli

## Initializes and installs project dependencies.
##
## Usage: fin init-deps

#-------------------------- BEGIN: Helper functions --------------------------------
SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT=${PROJECT_ROOT:-"${SCRIPT_PATH}/../../"}
source "${PROJECT_ROOT}/.docksal/functions.sh"

#-------------------------- CLOSE: Helper functions --------------------------------

#-------------------------- BEGIN: Execution --------------------------------

header "Dependency Installation"
section=Dependencies
step=1


step_header "Installing Composer"
if [[ "$RUN_AS_CI" = "true" ]]; then
  composer install --prefer-dist --no-dev --no-progress -o -n
else
  composer install
fi


step_header "Installing Node Packages"
run_command kit/npm install

#-------------------------- CLOSE: Execution --------------------------------
