#!/usr/bin/env bash

## Pre-deploy cleanup
##
## Usage: fin post-build

#-------------------------- BEGIN: Helper functions --------------------------------
SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT=${PROJECT_ROOT:-"${SCRIPT_PATH}/../../"}
source "${PROJECT_ROOT}/.docksal/functions.sh"

#-------------------------- CLOSE: Helper functions --------------------------------

#-------------------------- BEGIN: Execution --------------------------------

# ================================================ #
# Run ci post-build cleanup.                       #
# ================================================ #
header "Pre-deploy cleanup"
section="Pre-deploy"
step=1

if [[ "$RUN_AS_CI" = "true" ]]; then
  step_header "Removing files unnecessary for deployment"
  cd $PROJECT_ROOT
  rm -rf hooks/pre-commit
  rm -rf hooks/samples
  rm -rf patches
  rm -rf scripts/composer
  rm -rf source
  rm -rf .gitignore
  rm -rf .travis.yml
  rm -rf LICENSE
  rm -rf phpunit.xml.dist
  rm -rf readme.md
  rm -rf web/web.config
  # @note Don't remove composer.json file - Drush9 does not play well on Acquia if composer.json doesn't exist.
  # rm -rf composer.lock
  # rm -rf package.json
fi

#-------------------------- CLOSE: Execution --------------------------------
