name: Build and Lint

on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "feature/**", "main", "10.**" ]
  workflow_dispatch:
    # Inputs the workflow accepts.

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Linting w/ Grump
      run: |
        ls . | php ./vendor/bin/grumphp run
        find docroot/modules/custom/. | php ./vendor/bin/grumphp run
        find docroot/themes/custom/. | php ./vendor/bin/grumphp run
        find docroot/profiles/custom/. | php ./vendor/bin/grumphp run

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
