name: Profile Install Test
run-name: Testing installing the Enterprise profile.
on: [push]
env:
  LANDO_VERSION: v3.6.5
jobs:
  Install-Lando-And-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Lando
        run: |
          wget https://files.lando.dev/installer/lando-x64-stable.deb
          sudo dpkg -i lando-x64-stable.deb
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
              ${{ runner.os }}-php-
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}        
      - name: Copy Lando Yml
        run: cp .lando.profile.yml .lando.local.yml
      - name: Start Lando
        run: |
          lando --clear
          lando start
