name: Profile Install Test
run-name: Testing installing the Enterprise profile.
on: [push]
env:
  LANDO_VERSION: v3.14.0
jobs:
  Install-Lando-And-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Lando
        run: |
          curl -f#SL -o /tmp/lando.deb https://github.com/lando/lando/releases/download/v3.14.0/lando-x64-v3.14.0.deb; sudo dpkg -i --ignore-depends=docker-ce /tmp/lando.deb; rm -f /tmp/lando.deb; mkdir ~/.lando
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: | 
              ${{ runner.os }}-php-
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Copy Lando Yml
        run: cp .lando.profile.yml .lando.local.yml
      - name: Start Lando
        run: |
          lando --clear
          lando start
