name: Profile Install Test
run-name: Testing installing the Enterprise profile.
on: [push]
jobs:
  Install-Lando-And-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Lando
        run: |
          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-${{ matrix.lando.version }}"
          sudo chmod +x /usr/local/bin/lando
      - name: Setup Lando cache
        uses: actions/cache@v2
        with:
          path: ~/.lando/cache
          key: ${{ runner.os }}-lando${{ matrix.lando.version }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-lando${{ matrix.lando.version }}-
      - name: Copy Lando Yml
        run: cp .lando.profile.yml .lando.local.yml
      - name: Start Lando
        run: lando start
