name: Site Install Test
run-name: Testing installing the Enterprise profile.
on: [push]
env:
  LANDO_VERSION: v3.14.0
jobs:
  Install-Lando-And-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Lando
        uses: ./.github/workflows/install-lando
      - name: Copy Lando Yml
        run: cp .lando.profile.yml .lando.local.yml
      - name: List out lando files
        run: ls -Ra /home/runner/.lando
      - name: Start Lando
        run: lando start